### PR TITLE
12 task 2b primary locations work

### PR DESCRIPTION
**Pull request by Hussein-Mahfouz**
When complete, this PR will allow us to assign people to actual primary locations. See #12 for details

### CODE REVIEW

**Comment by Hussein-Mahfouz** [comment]
A couple of errors thrown by ruff that I think we could relax: 

> G004 Logging statement uses f-string
> EM101 Exception must not use a string literal, assign to variable first

What do you think @sgreenbury ?

**Comment by sgreenbury** [comment]
@Hussein-Mahfouz: this looks great, I have updated the notebook and scripts the following changes:
- Update region to Leeds only
- Transform CRS from 27700 to 4326 for centroids no longer included with SPC
- Update dep for uatk-spc
- Remove recoding at start of notebook since already recoded (in second script?)
- Fix remaining lints

It might be worth refactoring the scripts more extensively so their purpose is solely for processing the data (e.g. remove plots and other interactive aspects), but I think this would be better to look at in a new issue/PR.

**Comment by Hussein-Mahfouz** [comment]
Nice one! Happy to merge this :) 

> It might be worth refactoring the scripts more extensively so their purpose is solely for processing the data (e.g. remove plots and other interactive aspects), but I think this would be better to look at in a new issue/PR.

Yes agreed let's keep this one for a different PR. As discussed, the contents of the scripts might change so that we are dealing with all primary trips together

**Review by sgreenbury — APPROVED** [review]
Thanks @Hussein-Mahfouz, will go ahead and merge this now.

**Pull request merged**
